use std::{collections::HashMap, env, fs, path::{Path, PathBuf}, process, rc::Rc};

#[derive(Clone, Debug, PartialEq)]
enum Token {
    Name(String), Number(i64), Text(String), Plus, Minus, Star, Slash, Percent,
    EqEq, NotEq, Less, Greater, LessEq, GreaterEq, And, Or, LParen, RParen,
    LBracket, RBracket, LBrace, RBrace, Colon, Comma, End,
}

fn tokenize(source: &str) -> Result<Vec<Token>, String> {
    let chars: Vec<char> = source.chars().collect(); let mut i = 0; let mut out = Vec::new();
    while i < chars.len() {
        let c = chars[i];
        if c.is_whitespace() { i += 1; continue; }
        if c == '#' { while i < chars.len() && chars[i] != '\n' { i += 1; } continue; }
        if c.is_ascii_digit() { let s=i; while i<chars.len() && chars[i].is_ascii_digit(){i+=1;} out.push(Token::Number(chars[s..i].iter().collect::<String>().parse().unwrap())); continue; }
        if c.is_ascii_alphabetic() || c == '_' { let s=i; while i<chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i]=='_'){i+=1;} let word: String = chars[s..i].iter().collect(); out.push(match word.as_str() { "and" => Token::And, "or" => Token::Or, _ => Token::Name(word) }); continue; }
        if c == '"' { i+=1; let mut s=String::new(); while i<chars.len() && chars[i]!='"' { if chars[i]=='\\' && i+1<chars.len(){ i+=1; s.push(match chars[i]{'n'=>'\n','t'=>'\t','"'=>'"','\\'=>'\\',x=>x}); } else {s.push(chars[i]);} i+=1; } if i==chars.len(){return Err("unterminated string".into());} i+=1; out.push(Token::Text(s)); continue; }
        let t=match c {'+'=>Token::Plus,'-'=>Token::Minus,'*'=>Token::Star,'/'=>Token::Slash,'%'=>Token::Percent,'('=>Token::LParen,')'=>Token::RParen,'['=>Token::LBracket,']'=>Token::RBracket,'{'=>Token::LBrace,'}'=>Token::RBrace,':'=>Token::Colon,','=>Token::Comma,'=' if i+1<chars.len()&&chars[i+1]=='='=>{i+=1;Token::EqEq},'!' if i+1<chars.len()&&chars[i+1]=='='=>{i+=1;Token::NotEq},'<' if i+1<chars.len()&&chars[i+1]=='='=>{i+=1;Token::LessEq},'>' if i+1<chars.len()&&chars[i+1]=='='=>{i+=1;Token::GreaterEq},'<'=>Token::Less,'>'=>Token::Greater,_=>return Err(format!("unexpected character: {c}"))}; out.push(t); i+=1;
    }
    out.push(Token::End); Ok(out)
}

#[derive(Clone, Debug, PartialEq)]
struct Function { params: Vec<String>, body: Vec<String>, closure: HashMap<String,Value> }
#[derive(Clone, Debug, PartialEq)]
enum Value { Text(String), Number(i64), Bool(bool), List(Vec<Value>), Map(HashMap<String,Value>), None }
impl Value {
    fn show(&self)->String { match self { Self::Text(x)=>x.clone(),Self::Number(x)=>x.to_string(),Self::Bool(x)=>x.to_string(),Self::List(x)=>format!("[{}]",x.iter().map(Self::show).collect::<Vec<_>>().join(", ")),Self::Map(x)=>format!("{{{} keys}}",x.len()),Self::None=>"none".into() } }
    fn truthy(&self)->bool { match self {Self::Bool(x)=>*x,Self::Number(x)=>*x!=0,Self::Text(x)=>!x.is_empty(),Self::List(x)=>!x.is_empty(),Self::Map(x)=>!x.is_empty(),Self::None=>false} }
}

enum Flow { Continue, Break, LoopContinue, Return(Value) }
struct ExprParser<'a> { tokens:&'a [Token], pos:usize, vars:&'a HashMap<String,Value>, funcs:&'a HashMap<String,Rc<Function>> }
impl<'a> ExprParser<'a> {
    fn new(t:&'a [Token],v:&'a HashMap<String,Value>,f:&'a HashMap<String,Rc<Function>>)->Self{Self{tokens:t,pos:0,vars:v,funcs:f}}
    fn peek(&self)->&Token{&self.tokens[self.pos]}
    fn take(&mut self)->Token{let x=self.tokens[self.pos].clone();self.pos+=1;x}
    fn parse(&mut self,min:u8)->Result<Value,String>{
        let mut left=match self.take(){
            Token::Number(n)=>Value::Number(n),Token::Text(s)=>Value::Text(s),Token::Minus=>match self.parse(4)?{Value::Number(n)=>Value::Number(-n),_=>return Err("unary - expects a number".into())},
            Token::Name(n) if n=="true"=>Value::Bool(true),Token::Name(n) if n=="false"=>Value::Bool(false),Token::Name(n) if n=="not"=>Value::Bool(!self.parse(4)?.truthy()),Token::Name(n) if n=="none"=>Value::None,
            Token::Name(n) if n=="len" && *self.peek()==Token::LParen=>{self.take();let v=self.parse(0)?;if self.take()!=Token::RParen{return Err("expected ) after len".into());}match v{Value::List(x)=>Value::Number(x.len() as i64),Value::Text(x)=>Value::Number(x.chars().count() as i64),_=>return Err("len expects a list or text".into())}},
            Token::Name(n) if n=="str" && *self.peek()==Token::LParen=>{self.take();let v=self.parse(0)?;if self.take()!=Token::RParen{return Err("expected ) after str".into());}Value::Text(v.show())},
            Token::Name(n) if n=="json" && *self.peek()==Token::LParen=>{self.take();let v=self.parse(0)?;if self.take()!=Token::RParen{return Err("expected ) after json".into());}Value::Text(serde_json::to_string(&value_to_json(&v)).map_err(|e|format!("json encode failed: {e}"))?)},
            Token::Name(n) if n=="from_json" && *self.peek()==Token::LParen=>{self.take();let v=self.parse(0)?;if self.take()!=Token::RParen{return Err("expected ) after from_json".into());}match v{Value::Text(s)=>json_to_value(serde_json::from_str(&s).map_err(|e|format!("from_json failed: {e}"))?),_=>return Err("from_json expects text".into())}},
            Token::Name(n) if n=="range" && *self.peek()==Token::LParen=>{self.take();let first=self.parse(0)?;let (start,end)=if *self.peek()==Token::Comma{self.take();(first,self.parse(0)?)}else{(Value::Number(0),first)};if self.take()!=Token::RParen{return Err("expected ) after range".into());}match(start,end){(Value::Number(a),Value::Number(b)) if a<=b=>Value::List((a..b).map(Value::Number).collect()),_=>return Err("range expects numeric bounds".into())}},
            Token::Name(n) if n=="read_text" && *self.peek()==Token::LParen=>{self.take();let path=self.parse(0)?;if self.take()!=Token::RParen{return Err("expected ) after read_text".into());}match path{Value::Text(p)=>Value::Text(fs::read_to_string(p).map_err(|e|format!("read_text failed: {e}"))?),_=>return Err("read_text expects a text path".into())}},
            Token::Name(n) if n=="write_text" && *self.peek()==Token::LParen=>{self.take();let path=self.parse(0)?;if self.take()!=Token::Comma{return Err("expected comma in write_text".into());}let content=self.parse(0)?;if self.take()!=Token::RParen{return Err("expected ) after write_text".into());}match(path,content){(Value::Text(p),Value::Text(c))=>{fs::write(p,c).map_err(|e|format!("write_text failed: {e}"))?;Value::None},_=>return Err("write_text expects text path and content".into())}},
            Token::Name(n) if *self.peek()==Token::LParen=>{self.take();let mut args=Vec::new();if *self.peek()!=Token::RParen{loop{args.push(self.parse(0)?);if *self.peek()==Token::RParen{break;}if self.take()!=Token::Comma{return Err("expected comma in call".into());}}}self.take();let f=self.funcs.get(&n).ok_or(format!("undefined function: {n}"))?.clone();call_function(&f,args,self.funcs)?},
            Token::Name(n)=>self.vars.get(&n).cloned().ok_or(format!("undefined variable: {n}"))?,
            Token::LParen=>{let v=self.parse(0)?;if self.take()!=Token::RParen{return Err("expected )".into());}v},
            Token::LBracket=>{let mut x=Vec::new();if *self.peek()!=Token::RBracket{loop{x.push(self.parse(0)?);if *self.peek()==Token::RBracket{break;}if self.take()!=Token::Comma{return Err("expected comma".into());}}}self.take();Value::List(x)},
            Token::LBrace=>{let mut m=HashMap::new();if *self.peek()!=Token::RBrace{loop{let k=match self.take(){Token::Text(s)|Token::Name(s)=>s,_=>return Err("map key must be text or name".into())};if self.take()!=Token::Colon{return Err("expected : in map".into());}m.insert(k,self.parse(0)?);if *self.peek()==Token::RBrace{break;}if self.take()!=Token::Comma{return Err("expected comma in map".into());}}}self.take();Value::Map(m)},
            x=>return Err(format!("unexpected token: {x:?}")),
        };
        loop { if *self.peek()==Token::LBracket{self.take();let idx=self.parse(0)?;if self.take()!=Token::RBracket{return Err("expected ]".into());}left=match(left,idx){(Value::List(x),Value::Number(n)) if n>=0=>x.get(n as usize).cloned().ok_or("index out of range".to_string())?,(Value::Map(m),Value::Text(k))=>m.get(&k).cloned().ok_or("key not found".to_string())?,_=>return Err("invalid index operation".into())};continue;}let op=self.peek().clone();let p=match op{Token::EqEq|Token::NotEq|Token::Less|Token::Greater|Token::LessEq|Token::GreaterEq|Token::And|Token::Or=>1,Token::Plus|Token::Minus=>2,Token::Star|Token::Slash|Token::Percent=>3,_=>0};if p==0||p<min{break;}self.take();left=operate(left,op,self.parse(p+1)?)?;}Ok(left)
    }
}
fn operate(a:Value,op:Token,b:Value)->Result<Value,String>{match(a,op,b){(Value::Number(x),Token::Plus,Value::Number(y))=>Ok(Value::Number(x+y)),(Value::Number(x),Token::Minus,Value::Number(y))=>Ok(Value::Number(x-y)),(Value::Number(x),Token::Star,Value::Number(y))=>Ok(Value::Number(x*y)),(Value::Number(_),Token::Slash,Value::Number(0))=>Err("division by zero".into()),(Value::Number(x),Token::Slash,Value::Number(y))=>Ok(Value::Number(x/y)),(Value::Number(x),Token::Percent,Value::Number(y))=>Ok(Value::Number(x%y)),(Value::Text(x),Token::Plus,Value::Text(y))=>Ok(Value::Text(x+&y)),(Value::Bool(x),Token::And,Value::Bool(y))=>Ok(Value::Bool(x&&y)),(Value::Bool(x),Token::Or,Value::Bool(y))=>Ok(Value::Bool(x||y)),(x,Token::EqEq,y)=>Ok(Value::Bool(x==y)),(x,Token::NotEq,y)=>Ok(Value::Bool(x!=y)),(Value::Number(x),Token::Less,Value::Number(y))=>Ok(Value::Bool(x<y)),(Value::Number(x),Token::Greater,Value::Number(y))=>Ok(Value::Bool(x>y)),(Value::Number(x),Token::LessEq,Value::Number(y))=>Ok(Value::Bool(x<=y)),(Value::Number(x),Token::GreaterEq,Value::Number(y))=>Ok(Value::Bool(x>=y)),_=>Err("invalid operation".into())}}
fn value_to_json(v:&Value)->serde_json::Value{match v{Value::None=>serde_json::Value::Null,Value::Bool(x)=>serde_json::Value::Bool(*x),Value::Number(x)=>serde_json::Value::Number((*x).into()),Value::Text(x)=>serde_json::Value::String(x.clone()),Value::List(xs)=>serde_json::Value::Array(xs.iter().map(value_to_json).collect()),Value::Map(m)=>serde_json::Value::Object(m.iter().map(|(k,v)|(k.clone(),value_to_json(v))).collect())}}
fn json_to_value(v:serde_json::Value)->Value{match v{serde_json::Value::Null=>Value::None,serde_json::Value::Bool(x)=>Value::Bool(x),serde_json::Value::Number(x)=>Value::Number(x.as_i64().unwrap_or(0)),serde_json::Value::String(x)=>Value::Text(x),serde_json::Value::Array(xs)=>Value::List(xs.into_iter().map(json_to_value).collect()),serde_json::Value::Object(m)=>Value::Map(m.into_iter().map(|(k,v)|(k,json_to_value(v))).collect())}}
fn expression(raw:&str,vars:&HashMap<String,Value>,funcs:&HashMap<String,Rc<Function>>)->Result<Value,String>{ExprParser::new(&tokenize(raw)?,vars,funcs).parse(0)}
fn indented(lines:&[String],start:usize)->(Vec<String>,usize){let mut i=start;let mut body=Vec::new();while i<lines.len()&&(lines[i].starts_with(' ')||lines[i].starts_with('\t')){let line=&lines[i];let normalized=if line.starts_with('\t'){line[1..].to_string()}else{line.strip_prefix("    ").unwrap_or(line).to_string()};body.push(normalized);i+=1;}(body,i)}
fn call_function(f:&Function,args:Vec<Value>,funcs:&HashMap<String,Rc<Function>>)->Result<Value,String>{if args.len()!=f.params.len(){return Err(format!("function expects {} arguments, got {}",f.params.len(),args.len()));}let mut local=f.closure.clone();for(k,v)in f.params.iter().zip(args){local.insert(k.clone(),v);}let mut local_funcs=funcs.clone();match execute_lines(&f.body,&mut local,&mut local_funcs,Path::new("."))?{Flow::Return(v)=>Ok(v),Flow::Continue=>Ok(Value::None),Flow::Break|Flow::LoopContinue=>Err("break/continue cannot be used outside a loop".into())}}
fn execute_lines(lines:&[String],vars:&mut HashMap<String,Value>,funcs:&mut HashMap<String,Rc<Function>>,base:&Path)->Result<Flow,String>{let mut i=0;while i<lines.len(){let line=lines[i].trim();if line.is_empty()||line.starts_with('#'){i+=1;continue;}
    if let Some(rest)=line.strip_prefix("fn ").or_else(||line.strip_prefix("def ")){let head=rest.trim_end_matches(':');let(name,args)=head.split_once('(').ok_or("function syntax: fn name(a, b):".to_string())?;let args=args.trim_end_matches(')').split(',').filter(|x|!x.trim().is_empty()).map(|x|x.trim().to_string()).collect();let(body,end)=indented(lines,i+1);funcs.insert(name.trim().into(),Rc::new(Function{params:args,body,closure:vars.clone()}));i=end;continue;}
    if let Some(rest)=line.strip_prefix("return"){let v=if rest.trim().is_empty(){Value::None}else{expression(rest.trim(),vars,funcs)?};return Ok(Flow::Return(v));}
    if line=="break"{return Ok(Flow::Break);} if line=="continue"{return Ok(Flow::LoopContinue);}
    if let Some(c)=line.strip_prefix("while "){let condition=c.trim_end_matches(':').trim();let(body,end)=indented(lines,i+1);let mut guard=0;while expression(condition,vars,funcs)?.truthy(){match execute_lines(&body,vars,funcs,base)?{Flow::Return(v)=>return Ok(Flow::Return(v)),Flow::Break=>break,Flow::LoopContinue=>{},Flow::Continue=>{}}guard+=1;if guard>100000{return Err("loop limit exceeded".into());}}i=end;continue;}
    if let Some(rest)=line.strip_prefix("for "){let(name,src)=rest.trim_end_matches(':').split_once(" in ").ok_or("for syntax: for item in list:".to_string())?;let value=expression(src.trim(),vars,funcs)?;let(body,end)=indented(lines,i+1);match value{Value::List(items)=>for item in items{vars.insert(name.trim().into(),item);match execute_lines(&body,vars,funcs,base)?{Flow::Return(v)=>return Ok(Flow::Return(v)),Flow::Break=>break,Flow::LoopContinue=>continue,Flow::Continue=>{} }},_=>return Err("for expects a list".into())}i=end;continue;}
    if let Some(c)=line.strip_prefix("if "){let take=expression(c.trim_end_matches(':').trim(),vars,funcs)?.truthy();let(body,mut end)=indented(lines,i+1);if take{match execute_lines(&body,vars,funcs,base)?{Flow::Continue=>{},flow=>return Ok(flow)}}if end<lines.len()&&lines[end].trim()=="else:"{let(else_body,e)=indented(lines,end+1);if !take{match execute_lines(&else_body,vars,funcs,base)?{Flow::Continue=>{},flow=>return Ok(flow)}}end=e;}i=end;continue;}
    if let Some(x)=line.strip_prefix("say "){println!("{}",expression(x,vars,funcs)?.show());i+=1;continue;}
    if let Some(x)=line.strip_prefix("use "){let spec=x.trim();if spec.starts_with('"')||spec.contains('/')||spec.ends_with(".zp"){let raw=spec.trim_matches('"');let candidate=if Path::new(raw).extension().is_some(){raw.to_string()}else{format!("{raw}.zp")};let path=if Path::new(&candidate).is_absolute(){Path::new(&candidate).to_path_buf()}else{resolve_module(base,raw).ok_or(format!("module not found: {raw}"))?};let imported=fs::read_to_string(&path).map_err(|e|format!("cannot import {}: {e}",path.display()))?;let imported_lines=imported.lines().map(str::to_string).collect::<Vec<_>>();match execute_lines(&imported_lines,vars,funcs,base)?{Flow::Continue=>{},Flow::Return(_)=>return Err("return is not allowed at module top level".into()),flow=>return Ok(flow)}}else{println!("[Zap native] module declared: {spec}");}i+=1;continue;}
    if let Some(x)=line.strip_prefix("let "){let(n,v)=x.split_once('=').ok_or(format!("line {}: expected =",i+1))?;vars.insert(n.trim().into(),expression(v,vars,funcs)?);i+=1;continue;}
    if let Some((n,v))=line.split_once('='){vars.insert(n.trim().into(),expression(v,vars,funcs)?);i+=1;continue;}
    let _ = expression(line,vars,funcs)?; i+=1; continue;}Ok(Flow::Continue)}

fn run(source:&str,base:&Path)->Result<(),String>{let mut vars=HashMap::new();let mut funcs=HashMap::new();let lines=source.lines().map(str::to_string).collect::<Vec<_>>();match execute_lines(&lines,&mut vars,&mut funcs,base)?{Flow::Continue|Flow::Return(_)=>Ok(()),Flow::Break|Flow::LoopContinue=>Err("break/continue must be inside a loop".into())}}
fn format_source(source:&str)->String{let mut out=String::new();for line in source.lines(){let normalized=line.replace('\t',"    ").trim_end().to_string();out.push_str(&normalized);out.push('\n');}out}
fn manifest_value(text:&str,key:&str)->Option<String>{for line in text.lines(){let line=line.trim();if line.starts_with('#')||!line.starts_with(key){continue;}if let Some((k,v))=line.split_once('='){if k.trim()==key{return Some(v.trim().trim_matches('"').to_string());}}}None}
fn validate_project(dir:&Path)->Result<String,String>{let manifest=dir.join("zap.toml");let text=fs::read_to_string(&manifest).map_err(|e|format!("cannot read {}: {e}",manifest.display()))?;let name=manifest_value(&text,"name").ok_or("zap.toml: missing package name".to_string())?;let version=manifest_value(&text,"version").ok_or("zap.toml: missing package version".to_string())?;let main=manifest_value(&text,"main").unwrap_or_else(||"main.zp".into());if !dir.join(&main).is_file(){return Err(format!("zap.toml: main file not found: {}",dir.join(&main).display()));}Ok(format!("{name} {version} (main: {main})"))}
fn resolve_module(base:&Path,raw:&str)->Option<PathBuf>{let candidate=if Path::new(raw).extension().is_some(){raw.to_string()}else{format!("{raw}.zp")};let candidates=[base.join(&candidate),base.join("modules").join(&candidate),base.join("lib").join(&candidate)];candidates.into_iter().find(|p|p.is_file())}
fn main(){let args:Vec<String>=env::args().collect();if args.len()==2&&(args[1]=="--version"||args[1]=="-V"){println!("zap 0.3.0 (native)");return;}if args.len()==2&&(args[1]=="--help"||args[1]=="-h"){println!("Zap native runtime\n\nUsage:\n  zap <file.zp>       Run a Zap source file\n  zap fmt <file.zp>   Format a Zap source file\n  zap check [dir]      Validate zap.toml and the project entry file\n  zap --version        Show the version\n  zap --help           Show this help");return;}if args.len()==2&&args[1]=="check"{let dir=Path::new(".");match validate_project(dir){Ok(info)=>println!("valid Zap project: {info}"),Err(e)=>{eprintln!("Zap check error: {e}");process::exit(1);}}return;}if args.len()==3&&args[1]=="check"{let dir=Path::new(&args[2]);match validate_project(dir){Ok(info)=>println!("valid Zap project: {info}"),Err(e)=>{eprintln!("Zap check error: {e}");process::exit(1);}}return;}if args.len()==3&&args[1]=="fmt"{let path=Path::new(&args[2]);let source=fs::read_to_string(path).unwrap_or_else(|e|{eprintln!("cannot read {}: {e}",path.display());process::exit(1);});fs::write(path,format_source(&source)).unwrap_or_else(|e|{eprintln!("cannot write {}: {e}",path.display());process::exit(1);});return;}if args.len()!=2{eprintln!("Usage: zap <file.zp>\n       zap fmt <file.zp>\n       zap check [dir]\n       zap --version");process::exit(2);}let source=fs::read_to_string(&args[1]).unwrap_or_else(|e|{eprintln!("{e}");process::exit(1);});let base=Path::new(&args[1]).parent().unwrap_or(Path::new("."));if let Err(e)=run(&source,base){eprintln!("Zap error: {e}");process::exit(1);}}
