use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use super::{
    manifest_value, read_limited_text, run, validate_function_calls, validate_function_returns,
    validate_function_signatures,
};

pub(crate) fn validate_project(dir: &Path) -> Result<String, String> {
    let manifest = dir.join("zap.toml");
    let text = read_limited_text(&manifest, "manifest read")?;
    let name = manifest_value(&text, "name").ok_or("zap.toml: missing package name".to_string())?;
    let version =
        manifest_value(&text, "version").ok_or("zap.toml: missing package version".to_string())?;
    let main = manifest_value(&text, "main").unwrap_or_else(|| "main.zp".into());
    let main_path = dir.join(&main);
    if !main_path.is_file() {
        return Err(format!(
            "zap.toml: main file not found: {}",
            main_path.display()
        ));
    }
    validate_lockfile(dir, &text)?;
    let source = read_limited_text(&main_path, "source read")?;
    validate_function_signatures(&source, &main_path)?;
    validate_function_returns(&source, &main_path)?;
    validate_function_calls(&source, &main_path)?;
    Ok(format!("{name} {version} (main: {main})"))
}

fn parse_dependencies(manifest: &str) -> Result<BTreeMap<String, String>, String> {
    let mut dependencies = BTreeMap::new();
    let mut in_dependencies = false;
    for raw_line in manifest.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') {
            in_dependencies = line == "[dependencies]";
            continue;
        }
        if !in_dependencies {
            continue;
        }
        let (name, value) = line
            .split_once('=')
            .ok_or_else(|| format!("zap.toml: invalid dependency entry `{line}`"))?;
        let name = name.trim();
        let version = value.trim().trim_matches('"');
        if name.is_empty() || version.is_empty() || name.contains(char::is_whitespace) {
            return Err(format!("zap.toml: invalid dependency entry `{line}`"));
        }
        if dependencies
            .insert(name.to_string(), version.to_string())
            .is_some()
        {
            return Err(format!("zap.toml: duplicate dependency `{name}`"));
        }
    }
    Ok(dependencies)
}

fn canonical_lockfile(
    name: &str,
    version: &str,
    dependencies: &BTreeMap<String, String>,
) -> String {
    let mut output = String::from("# This file is generated by Zap. Do not edit manually.\nlockfile_version = 1\n\n[package]\n");
    output.push_str(&format!(
        "name = \\\"{name}\\\"\nversion = \\\"{version}\\\"\n\n[dependencies]\n"
    ));
    for (dependency, requirement) in dependencies {
        output.push_str(&format!("{dependency} = \\\"{requirement}\\\"\n"));
    }
    output
}

fn validate_lockfile(dir: &Path, manifest: &str) -> Result<(), String> {
    let dependencies = parse_dependencies(manifest)?;
    let lock_path = dir.join("zap.lock");
    if dependencies.is_empty() {
        return Ok(());
    }
    let name = manifest_value(manifest, "name").unwrap_or_default();
    let version = manifest_value(manifest, "version").unwrap_or_default();
    let expected = canonical_lockfile(&name, &version, &dependencies);
    let actual = fs::read_to_string(&lock_path)
        .map_err(|_| "zap.lock: missing lockfile; run `zap lock` to generate it".to_string())?;
    if actual != expected {
        return Err(
            "zap.lock: out of date or non-canonical; run `zap lock` to regenerate it".into(),
        );
    }
    Ok(())
}

pub(crate) fn add_dependency(dir: &Path, name: &str, requirement: &str) -> Result<String, String> {
    if name.is_empty() || name.contains(char::is_whitespace) || name.contains('=') {
        return Err(format!("invalid dependency name `{name}`"));
    }
    if requirement.is_empty() || requirement.contains('"') || requirement.contains('\n') {
        return Err("dependency requirement must be a non-empty single-line value".to_string());
    }
    let manifest_path = dir.join("zap.toml");
    let manifest = read_limited_text(&manifest_path, "manifest read")?;
    let mut lines: Vec<String> = manifest.lines().map(str::to_string).collect();
    let mut section_start = None;
    let mut section_end = lines.len();
    for (index, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        if trimmed == "[dependencies]" {
            section_start = Some(index);
            continue;
        }
        if section_start.is_some() && trimmed.starts_with('[') {
            section_end = index;
            break;
        }
    }
    let entry = format!("{name} = \"{requirement}\"");
    match section_start {
        Some(start) => {
            let end = section_end;
            let mut dependencies = parse_dependencies(&manifest)?;
            if dependencies.contains_key(name) {
                return Err(format!("dependency already exists: `{name}`"));
            }
            dependencies.insert(name.to_string(), requirement.to_string());
            let mut replacement = vec!["[dependencies]".to_string()];
            for (dependency, value) in dependencies {
                replacement.push(format!("{dependency} = \"{value}\""));
            }
            lines.splice(start..end, replacement);
        }
        None => {
            if !lines.is_empty() && lines.last().is_some_and(|line| !line.is_empty()) {
                lines.push(String::new());
            }
            lines.push("[dependencies]".to_string());
            lines.push(entry);
        }
    }
    let mut updated = lines.join("\n");
    updated.push('\n');
    fs::write(&manifest_path, updated)
        .map_err(|e| format!("zap.toml: cannot write manifest: {e}"))?;
    let lock_path = dir.join("zap.lock");
    if lock_path.exists() {
        fs::remove_file(lock_path)
            .map_err(|e| format!("zap.lock: cannot invalidate lockfile: {e}"))?;
    }
    Ok(format!("added dependency `{name}` = \"{requirement}\""))
}

pub(crate) fn write_lockfile(dir: &Path) -> Result<String, String> {
    let manifest_path = dir.join("zap.toml");
    let manifest = read_limited_text(&manifest_path, "manifest read")?;
    let name =
        manifest_value(&manifest, "name").ok_or("zap.toml: missing package name".to_string())?;
    let version = manifest_value(&manifest, "version")
        .ok_or("zap.toml: missing package version".to_string())?;
    let dependencies = parse_dependencies(&manifest)?;
    let content = canonical_lockfile(&name, &version, &dependencies);
    fs::write(dir.join("zap.lock"), content)
        .map_err(|e| format!("zap.lock: cannot write lockfile: {e}"))?;
    Ok(format!(
        "wrote zap.lock with {} dependencies",
        dependencies.len()
    ))
}

pub(crate) fn resolve_module(base: &Path, raw: &str) -> Option<PathBuf> {
    let candidate = if Path::new(raw).extension().is_some() {
        raw.to_string()
    } else {
        format!("{raw}.zp")
    };
    let candidates = [
        base.join(&candidate),
        base.join("modules").join(&candidate),
        base.join("lib").join(&candidate),
    ];
    candidates.into_iter().find(|p| p.is_file())
}

pub(crate) fn collect_test_files(dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in fs::read_dir(dir)
        .map_err(|e| format!("cannot read test directory {}: {e}", dir.display()))?
    {
        let path = entry
            .map_err(|e| format!("cannot inspect test directory {}: {e}", dir.display()))?
            .path();
        if path.is_dir() {
            collect_test_files(&path, files)?;
        } else if path.extension().and_then(|x| x.to_str()) == Some("zp")
            && path
                .file_stem()
                .and_then(|x| x.to_str())
                .map(|x| x.ends_with("_test"))
                .unwrap_or(false)
        {
            files.push(path);
        }
    }
    Ok(())
}

#[derive(Clone, Debug, Default)]
pub(crate) struct TestOptions {
    pub(crate) filter: Option<String>,
    pub(crate) fail_fast: bool,
    pub(crate) json: bool,
}

struct TestResult {
    path: PathBuf,
    passed: bool,
    error: Option<String>,
}

fn json_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

fn print_test_report(results: &[TestResult], skipped: usize, json: bool) {
    let passed = results.iter().filter(|result| result.passed).count();
    let failed = results.len() - passed;
    if json {
        let cases = results
            .iter()
            .map(|result| {
                let error = result
                    .error
                    .as_deref()
                    .map(|value| format!("\"{}\"", json_escape(value)))
                    .unwrap_or_else(|| "null".to_string());
                format!(
                    "{{\"path\":\"{}\",\"passed\":{},\"error\":{}}}",
                    json_escape(&result.path.display().to_string()),
                    result.passed,
                    error
                )
            })
            .collect::<Vec<_>>()
            .join(",");
        println!(
            "{{\"passed\":{},\"failed\":{},\"skipped\":{},\"tests\":[{}]}}",
            passed, failed, skipped, cases
        );
    } else {
        println!(
            "test result: {} passed; {} failed; {} skipped",
            passed, failed, skipped
        );
    }
}

pub(crate) fn run_zap_tests(dir: &Path, options: &TestOptions) -> Result<usize, String> {
    let mut files = Vec::new();
    collect_test_files(dir, &mut files)?;
    files.sort();
    let selected = files
        .into_iter()
        .filter(|path| {
            options
                .filter
                .as_deref()
                .map(|filter| path.display().to_string().contains(filter))
                .unwrap_or(true)
        })
        .collect::<Vec<_>>();
    if selected.is_empty() {
        return Err(match &options.filter {
            Some(filter) => format!(
                "no test files matched filter `{filter}` in {}",
                dir.display()
            ),
            None => format!("no *_test.zp files found in {}", dir.display()),
        });
    }

    let selected_count = selected.len();
    let mut results = Vec::new();
    for path in selected {
        let outcome = read_limited_text(&path, "test read")
            .and_then(|source| run(&source, path.parent().unwrap_or(Path::new("."))));
        match outcome {
            Ok(()) => {
                if !options.json {
                    println!("ok   {}", path.display());
                }
                results.push(TestResult {
                    path,
                    passed: true,
                    error: None,
                });
            }
            Err(error) => {
                if !options.json {
                    eprintln!("FAIL {}: {}", path.display(), error);
                }
                results.push(TestResult {
                    path,
                    passed: false,
                    error: Some(error),
                });
                if options.fail_fast {
                    break;
                }
            }
        }
    }

    let skipped = selected_count.saturating_sub(results.len());
    print_test_report(&results, skipped, options.json);
    let passed = results.iter().filter(|result| result.passed).count();
    if results.iter().any(|result| !result.passed) {
        Err(format!("{} test file(s) failed", results.len() - passed))
    } else {
        Ok(passed)
    }
}
